image: openjdk:10-jdk

stages:
    - build
    - publish
    - deploy

before_script:
  - echo $GRADLE_HOME
  - echo `pwd`
  - export GRADLE_USER_HOME=`pwd`/.gradle
  - rm -f  .gradle/caches/modules-2/modules-2.lock
  - rm -fr .gradle/caches/*/plugin-resolution/
  - chmod +x gradlew
cache:
  paths:
    - .gradle/wrapper
    - .gradle/caches

build:gradle:
  stage: build
  only:
    - master
  script:
    - ./gradlew buildAndReport
  artifacts:
    name: "$CI_JOB_NAME"
    paths:
    - ./build/reports/tests/
    - ./build/reports/checkstyle/
    - ./build/jacocoHtml
    expire_in: 1 week

pages:
    stage: publish
    
    dependencies:
      - build:gradle

    script:
      - mv build/reports/tests/ public/
      - mv build/reports/checkstyle/ public/
      - mv build/jacocoHtml public/


    artifacts:
      paths:
        - public
    only:
      - master