image: openjdk:10-jdk

stages:
    - build
    - publish
    - deploy

before_script:
  - echo $GRADLE_HOME
  - echo `pwd`
  - export GRADLE_USER_HOME=`pwd`/.gradle
  - rm -f  .gradle/caches/modules-2/modules-2.lock
  - rm -fr .gradle/caches/*/plugin-resolution/
  - chmod +x gradlew
cache:
  paths:
    - .gradle/wrapper
    - .gradle/caches

build:gradle:
  stage: build
  only:
    - master
  script:
    - ./gradlew buildAndReport
  artifacts:
    name: "$CI_JOB_NAME"
    paths:
    - ./build/reports/tests/
    - ./build/reports/checkstyle/
    - ./build/jacocoHtml
    expire_in: 1 week

pages:
    stage: publish

    script:
      - echo 'Copy test results'
      - pwd
      - echo 'Files'
      - echo '-----'
      - ls -lR
      - mkdir .public
      - cd .public
      - echo "<HTML><HEAD></HEAD><BODY><H1>Latest Test Report</H1><DIV><A href=./tests/test/>Results</A></DIV></BODY></HTML>" > index.html
      - cd ..
      - pwd
      - cp -r ./build/reports/tests/ .public
      - cp -r ./build/reports/checkstyle/ .public
      - cp -r ./build/jacocoHtml/ .public
      - ls -lR .public
      - mv .public ./public
      - pwd
      - ls -lR

    artifacts:
      paths:
        - public
    only:
      - master